// Prototype copy stays together until the feature and its production semantics
// are accepted. The shared application language preference still selects it.
const zh = {
  badge: "互动实验室", title: "沙发上，热闹一点。", subtitle: "听房主聊两句，顺手丢个番茄。",
  room: "房间", name: "昵称", enter: "入座", leave: "离开", retry: "重新加入",
  invite: "再开一个标签页", inviteHint: "以另一位参与者加入同一房间", copy: "复制邀请链接", copied: "已复制",
  connected: "已入座", notConnected: "未连接", you: "你",
  effects: "道具动效", target: "丢给", select: "点一下沙发上的朋友，选个道具。",
  propsWaiting: "开始分享后，可以给朋友丢个道具。",
  tomato: "番茄", poop: "便便", heart: "比心",
  micOn: "开启麦克风", micOff: "麦克风静音", micPending: "等待麦克风授权…",
  display: "分享屏幕 / 窗口", displayPending: "正在选择画面…", stopShare: "停止分享",
  camera: "分享摄像头", cameraPending: "等待摄像头授权…",
  chooseSource: "先选画面，再按需开启麦克风。", waitingHost: "等房主选好画面。",
  hostMicOff: "房主麦克风未开启", hostMicOn: "房主麦克风已开启", connectingMedia: "正在连接房主…",
  playAudio: "点击播放", muteOutput: "关闭接收声音", unmuteOutput: "开启接收声音",
  stage: "共享画面", demoStage: "示意画面", cameraStage: "摄像头画面", displayStage: "屏幕 / 窗口画面",
  prototype: "本地原型 · 房主开麦 · 摄像头分享 · 表情互动",
  guide: "第一个标签页是房主，后续标签页是观众。房主选择屏幕、窗口、浏览器标签页或摄像头分享，再按需开麦。测试时请戴耳机。",
  close: "关闭提示", cameraHint: "麦克风与分享声音一起传给观众。手机可以选择摄像头；设备采集需要 HTTPS 或本机地址。",
  errors: {
    "room-full": "房间坐满了，请换一个房间号。", "host-only": "只有房主可以分享画面或开启麦克风。",
    "host-left": "房主已离开，这个原型房间已结束。",
    "not-sharing": "等房主开始分享后，再丢道具吧。",
    "slow-down": "稍等一下，再来一个。", invalid: "这次操作未被接受，请重试。", "target-left": "这位朋友已经离开了。",
    disconnected: "房间连接已断开。重新加入即可继续。", "media-failed": "音视频连接失败，请离开房间后重新加入。",
    permission: "未获得设备权限。请在浏览器中允许访问后重试。", "device-unavailable": "无法打开设备，请检查是否被其他应用占用。",
    "screen-unavailable": "这个浏览器不支持屏幕分享，可以选择摄像头。",
    clipboard: "复制失败，请复制地址栏里的链接。",
  },
};
type Copy = { [K in keyof typeof zh]: K extends "errors" ? Record<keyof typeof zh.errors, string> : string };
const en: Copy = {
  badge: "Interaction lab", title: "A little more company.", subtitle: "Listen to your host. Toss a tomato.",
  room: "Room", name: "Name", enter: "Take a seat", leave: "Leave", retry: "Rejoin",
  invite: "Open another tab", inviteHint: "Join this room as another participant", copy: "Copy invitation", copied: "Copied",
  connected: "Seated", notConnected: "Not connected", you: "You",
  effects: "Prop animations", target: "Toss to", select: "Pick a friend on the couch, then a prop.",
  propsWaiting: "Once sharing starts, pick a friend and toss a prop.",
  tomato: "Tomato", poop: "Poop", heart: "Heart",
  micOn: "Enable microphone", micOff: "Mute microphone", micPending: "Waiting for microphone permission…",
  display: "Share screen / window", displayPending: "Choosing a screen…", stopShare: "Stop sharing",
  camera: "Share camera", cameraPending: "Waiting for camera permission…",
  chooseSource: "Choose what to share, then turn on your microphone if you like.", waitingHost: "Waiting for the host to choose a source.",
  hostMicOff: "Host microphone off", hostMicOn: "Host microphone on", connectingMedia: "Connecting to the host…",
  playAudio: "Click to play", muteOutput: "Mute incoming audio", unmuteOutput: "Unmute incoming audio",
  stage: "Shared screen", demoStage: "Illustrated preview", cameraStage: "Camera", displayStage: "Screen / window",
  prototype: "Local prototype · Host microphone · Camera sharing · Reactions",
  guide: "The first tab hosts; later tabs watch. Share a screen, window, browser tab or camera, then enable the host microphone if needed. Use headphones when testing.",
  close: "Dismiss", cameraHint: "Your microphone and shared audio reach viewers together. Phones can share a camera; device capture requires HTTPS or localhost.",
  errors: {
    "room-full": "This room is full. Try another room number.", "host-only": "Only the host can share a source or enable a microphone.",
    "host-left": "The host left. This prototype room has ended.",
    "not-sharing": "Wait for the host to start sharing before tossing a prop.",
    "slow-down": "Give it a moment before sending another.", invalid: "That action was not accepted. Please try again.", "target-left": "Your friend has left the room.",
    disconnected: "The room disconnected. Rejoin to continue.", "media-failed": "An audio/video connection failed. Leave the room and rejoin.",
    permission: "Device permission was not granted. Allow access in your browser and try again.", "device-unavailable": "The device could not start. Check whether another app is using it.",
    "screen-unavailable": "This browser cannot share a screen. You can share a camera instead.",
    clipboard: "Could not copy. Copy the link from your address bar instead.",
  },
};
export function interactionCopy(lang: string): Copy { return lang === "zh" ? zh : en; }
